// @ts-check
// Prepares DATABASE_URL for Prisma by falling back to PRISMA_DATABASE_URL.
// This handles Vercel's default naming convention (PRISMA_DATABASE_URL)
// while keeping the Prisma schema standardized on DATABASE_URL.

const fs = require("fs");
const path = require("path");

const dbUrl = process.env.DATABASE_URL || process.env.PRISMA_DATABASE_URL;

if (dbUrl) {
  process.env.DATABASE_URL = dbUrl;

  // Also write to .env so Prisma CLI & child processes pick it up
  const envPath = path.join(__dirname, "..", ".env");
  try {
    let content = "";
    try {
      content = fs.readFileSync(envPath, "utf-8");
    } catch {
      // .env doesn't exist yet
    }
    if (!content.includes("DATABASE_URL=")) {
      fs.appendFileSync(
        envPath,
        `\n# Auto-generated by scripts/prepare-db-url.js\nDATABASE_URL="${dbUrl}"\n`,
      );
    }
  } catch {
    // Silently fail — env will still work via process.env
  }
}
